---
title: "Predicting Stock Price Using Technical Indicators"
author: "Ha Le and Duong Pham"
date: "3/22/2022"
output: html_document
---

```{r setup, include=FALSE, echo=TRUE}
library(tidyr)
library(tidyverse)
library(dygraphs)
library(ggplot2)
library(xts)
library(forecast)
library(Metrics)
library(xgboost)
library(keras)
```

```{r}
#read in the dataset
price_df <- read_csv('../results/csvs/simplified_df.csv') %>% as_tibble()
input_stock <- 'ORS'
stock_df <- price_df %>% filter(stock_code == input_stock)
stock_df <- stock_df %>% filter(date >= as.Date('2017-01-01'))
stock_df
```
# Visualizing Stock Price Using  Dygraphs (Panel 1)

```{r}
data <- data.frame(
  time= stock_df$date, 
  value1=stock_df$open, 
  value2=stock_df$high, 
  value3=stock_df$low, 
  value4=stock_df$close 
)

# switch to xts format
data <- xts(x = data[,-1], order.by = data$time)

# Plot it
p <- dygraph(data) %>%
  dyCandlestick()
p
```
# Training and Fitting ARIMA model

```{r}
#create training and testing period
train1_df <- stock_df %>% 
  filter(stock_df$date >= as.Date('2021-06-01') & 
           stock_df$date <= as.Date('2021-12-31')) %>%
  select(c(date, close))
  
test1_df <- stock_df %>%
  filter(stock_df$date >= as.Date('2022-01-01')) %>%
  select(c(date, close))

```

```{r}
#train the model on the training set
arima <- auto.arima(train1_df$close)

# model summary
summary(arima)

# forecasting
forecast = predict(arima,length(test1_df$close))
# evaluation
rmse(test1_df$close, forecast$pred)
```

```{r}
# visualizing the result
predict_price <- cbind(forecast$pred, test1_df$close)
dygraph(predict_price)
```

# Predicting Stock Price Using multivariate algorithms
## XGBoost
```{r}
#create training and testing period
train1_df <- stock_df %>% 
  filter(stock_df$date >= as.Date('2021-06-01') & 
           stock_df$date <= as.Date('2021-12-31')) %>%
  select(-open, -changes, -adjust, -...1, -date, -stock_code, -low, -high)

test1_df <- stock_df %>% 
  filter(stock_df$date >= as.Date('2022-01-01')) %>%
  select(-open, -changes, -adjust, -...1, -date, -stock_code, -low, -high)

date <- stock_df %>% filter(stock_df$date >= as.Date('2022-01-01'))
date <- date$date

intercept_only <- lm(close ~ 1, data=train1_df)
all <- lm(close ~ ., data=train1_df)

backward <- step(all, direction='backward', scope=formula(all), trace=0)

backward$anova
backward$coefficients
summary(backward)
```

Visualizing the prediction
```{r}
library(modelr)
colors <- c("Real Closing Price" = "blue", "Predicted Closing Price" = "red")

# visualizing the result
test1_df <- test1_df %>% add_predictions(backward, var = "pred")
ggplot(test1_df, aes(x = date)) + 
  geom_line(aes(y = close, color = "Real Closing Price"), size = 0.5) +
  geom_line(aes(y = pred, color = "Predicted Closing Price"), size = 0.5) +
  labs(x = "Date",
         y = "closing prices",
         color = "Legend") +
  scale_color_manual(values = colors)

rmse(backward, train1_df)
```
# Predicting Using LSTM Vanilla model
## Building the structure of the LSTM

